services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqq
    ports:
      - "5672:5672" # Puerto para AMQP
      - "15672:15672" # Panel de administración http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitnet

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
    networks:
      - rabbitnet

  worker1:
    build: ./worker
    container_name: worker1
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - WORKER_ID=1
    networks:
      - rabbitnet

  worker2:
    build: ./worker
    container_name: worker2
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - WORKER_ID=2
    networks:
      - rabbitnet
  monitor:
    build:
      context: ./monitor
    container_name: monitor
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=admin
      - RABBIT_PASS=admin
    networks:
      - rabbitnet
networks:
  rabbitnet:
    driver: bridge
